[package]
name = "graph-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "stream"] }
oauth2 = "4"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
url = "2"
percent-encoding = "2"
futures.workspace = true
tokio-util = { version = "0.7", features = ["io"] }
bytes = "1"
dirs.workspace = true
