[package]
name = "vfs"
version = "0.1.0"
edition = "2021"

[dependencies]
fuse3 = { version = "0.7", features = ["tokio-runtime", "unprivileged"] }
sync-engine = { path = "../sync-engine" }
graph-client = { path = "../graph-client" }
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
libc.workspace = true
futures.workspace = true
bytes = "1"
chrono.workspace = true
